export const meta = {
  name: 'booklets-review',
  description: 'Max-effort multi-dimension review of the mo-elbooklets working diff, with adversarial verification of every finding',
  whenToUse: 'Invoked by the booklets-review skill in place of the built-in /code-review, which the model cannot call. Reviews the ElBooklets diff across project-specific dimensions (debug gate, GraphQL contract, OTP contract, quiz invariants, i18n/RTL/fonts, tests) and returns only findings that survive a refutation panel.',
  phases: [
    { title: 'Review', detail: 'one max-effort reviewer per applicable dimension' },
    { title: 'Verify', detail: '3 independent skeptics per finding; 2-of-3 to survive' },
    { title: 'Synthesize', detail: 'rank, dedupe, and report what the fan-out missed' },
  ],
}

// ---------------------------------------------------------------------------
// args: { base, head, scopeNote, changedFiles }
//   base         — ref to diff against ("main", or "HEAD" for the working tree)
//   head         — "HEAD"; uncommitted changes are always included
//   changedFiles — array of repo-relative paths; gates which dimensions run
// ---------------------------------------------------------------------------

const base = (args && args.base) || 'main'
const head = (args && args.head) || 'HEAD'
const scopeNote = (args && args.scopeNote) || ''
const changedFiles = (args && args.changedFiles) || []

// Path-based dimension gating. With no file list every dimension runs — a
// missed dimension is worse than a wasted one.
const touches = (re) => !changedFiles.length || changedFiles.some((f) => re.test(f))

const hasGraphql = touches(/\.graphql$|src\/generated\/|apollo|Document|useQuery|useMutation/i)
const hasAuth = touches(/auth|otp|login|register|password|session|token|secure-store/i)
const hasQuiz = touches(/quiz|question|answer|score|match|paragraph/i)
const hasUi = touches(/\.tsx$|locales\/|i18n|config\/(colors|fonts|spacing|layout)/i)
const hasTests = touches(/__tests__|\.test\.|\.spec\.|jest|e2e\//i)

const CONTEXT = `
Repo: mo-elbooklets (ElBooklets) — an Expo SDK 54 React Native education app for Egyptian
students, bilingual Arabic/English with RTL, plus a separate parent role.
Diff scope: base ${base} ... head ${head} (uncommitted changes included).
${scopeNote ? `Scope note: ${scopeNote}` : ''}

Gather the diff yourself, then read the full surrounding files for anything the diff
touches — a diff hunk alone is not enough context to judge correctness. The guard you are
about to report as missing is often forty lines above the hunk.

git diff ${base}...${head}
git diff
git diff --cached
git status --porcelain

Do NOT review android/ or ios/ (generated by Expo prebuild). src/generated/ and
src/graphql/schema.graphql are codegen / schema:pull output — a hand-edit there is itself a
blocker finding, but never review them for style.

Truth order when sources disagree: the code > CLAUDE.md > mobile-otp-guide.md > any other
markdown in the repo. Where the code contradicts CLAUDE.md, that drift is a finding in its
own right.

Report ONLY defects you can point at in the changed code. No style opinions, no "consider
extracting", no praise, no summary of what the diff does. If a dimension is clean, return
an empty findings array — that is a valid and useful result.
`.trim()

const RULES = `
Rules this codebase has actually been burned by:
- Debug gate: the OTP skip and every debug affordance is gated by isDebugMode() reading
  app.json > extra.debugMode ONLY. Widening it (__DEV__, emulator detection, an env var) is
  a merge blocker — a prod build must never show OTP skip.
- GraphQL discipline: every operation lives in a domain .graphql file under src/graphql/ and
  is consumed as a generated typed document. No inline gql tags or query strings in screens.
  src/generated/* and schema.graphql are never hand-edited (npm run codegen / schema:pull own
  them).
- Partial responses: the client runs errorPolicy: 'all', so a response can carry data AND
  field-level errors. Gate error states with loadFailureMessage() (src/utils/queryError.ts) —
  only a response with NO data is a load failure. Never blank a screen that has something to
  render.
- OTP contract (mobile-otp-guide.md): codes are scoped to purpose+audience so every flow
  starts with a fresh send; resend locked 60s after EVERY send including the automatic one;
  countdown from expires_in, never hardcoded; send success:false means rate-limited — show the
  server message, never auto-retry; send success:true says nothing about the account existing,
  so always advance to the code screen (anti-enumeration); after a successful password reset
  every token is revoked — clear the token and route to login, never auto-login.
- Arabic-Indic digits: never strip with an ASCII-only \\d / [^0-9] before normalizing — it
  silently deletes an Arabic code. normalizeDigits (src/utils/digits.ts) runs first.
- Quiz invariants: Question.type is one of six values — branch on type via the guards in
  src/utils/quizQuestionTypes.ts, never on answers.length. Scoring is unit-based (match = one
  per pair, paragraph = sum of children); xp is server-derived, never computed client-side.
  Submit is exactly one entry per TOP-LEVEL question via buildSubmitPayload. Results
  userAnswers is flat — regroup with groupUserAnswers; answer_1 is null for match/paragraph.
- i18n: no hardcoded user-facing strings — everything through t(), key added to BOTH
  src/i18n/locales/en.json and ar.json. The root /locales directory is stale; editing it is a
  finding.
- RTL: textAlign: 'left' and let native RTL flip it — EXCEPT TextInput, which uses
  INPUT_TEXT_ALIGN from src/lib/rtl.ts and must not also set textAlign in its style.
- Fonts: font follows the text's script, not the UI language — pass isArabicText(str) as
  forceArabic for user-supplied text. Never a bare fontWeight (drops the custom family on
  Android — use typography(style, weight) / fontWeight(weight)).
- Design tokens from src/config/ (colors, spacing, layout, fonts) — no hardcoded values.
- testIDs: kebab-case {screen}-{element} on every new interactive element.
- Regex on Hermes: explicit \\uXXXX ranges, never \\p{L} — an unsupported property escape is a
  bundle-load parse error. In an assembled character class the hyphen stays last.
- validators.ts is the single source of truth for name/password/mobile policy (registration
  password = min 8 chars). Never re-inline a copy.
- TypeScript strict: no any without a comment explaining why. Functional components only,
  StyleSheet.create() for styles. No Redux, NativeWind, or class components.
`.trim()

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          file: { type: 'string', description: 'repo-relative path' },
          line: { type: 'integer', description: '1-indexed line the defect anchors to' },
          category: { type: 'string', description: 'kebab-case slug, e.g. debug-gate-widening' },
          severity: { type: 'string', enum: ['blocker', 'high', 'medium', 'low'] },
          summary: { type: 'string', description: 'one sentence stating the defect' },
          failure_scenario: { type: 'string', description: 'concrete inputs/state -> wrong output, crash, or exposure' },
          evidence: { type: 'string', description: 'the code that proves it, plus any CLAUDE.md / guide reference' },
        },
        required: ['file', 'line', 'category', 'severity', 'summary', 'failure_scenario', 'evidence'],
      },
    },
  },
  required: ['findings'],
}

const VERDICT_SCHEMA = {
  type: 'object',
  properties: {
    refuted: { type: 'boolean', description: 'true if the finding does not hold' },
    reason: { type: 'string' },
    corrected_severity: { type: 'string', enum: ['blocker', 'high', 'medium', 'low', 'none'] },
  },
  required: ['refuted', 'reason', 'corrected_severity'],
}

// --- Dimensions ------------------------------------------------------------
// `applies` gates a dimension to the files actually changed.

const ALL_DIMENSIONS = [
  {
    key: 'security-debug-gate',
    applies: true,
    prompt: `Review for security defects and debug affordances leaking into production.

Hunt specifically for:
- isDebugMode() widened, shadowed, or bypassed — any path where the OTP skip buttons
  (otp-skip-debug, otp-skip-debug-2), the API URL switcher, or Reactotron could render in a
  build with app.json > extra.debugMode false. Check the actual call chain, not the name.
- a token, password, OTP code, or mobile number written to a log, analytics event, crash
  report, error message, or navigation param
- auth-token handling: a token read from or left in AsyncStorage instead of expo-secure-store,
  a token not cleared on logout / session revoke / password reset, a request that sends a stale
  token after revocation
- an authenticated mutation called on a path the user has not been authenticated for, or a
  guarded screen reachable without the gate
- anti-enumeration breaks: any UI that reveals whether a mobile number or email belongs to a
  registered account (wording, a different navigation outcome, a different error, a timing tell)
- real credentials or production secrets committed anywhere, especially e2e/env.yaml`,
  },
  {
    key: 'graphql-contract',
    applies: hasGraphql,
    prompt: `Review the GraphQL layer against this project's discipline.

Flag:
- an inline gql tag or query string in a screen/hook/service instead of a domain .graphql file
- a hand-edit to src/generated/* or src/graphql/schema.graphql (both are tool-owned)
- codegen drift: a .graphql operation edited without regenerating, or a generated document
  imported that no operation defines
- a selection set missing a field the consuming code reads (undefined at runtime), or a field
  selected that the schema does not define
- error handling that ignores errorPolicy: 'all' — treating a partial response (data AND
  errors) as a total failure and blanking a screen that has something to render, or the
  reverse: rendering as success when data is null. loadFailureMessage() in
  src/utils/queryError.ts is the intended gate.
- a mutation whose variables do not match the schema's argument names/nullability
- Apollo cache hazards: a type with colliding ids needing keyFields: false (MatchColumnItem is
  the precedent), a refetch that leaves stale data, a write that does not update the cache
- a long-running mutation without the longer per-op timeout where one is warranted`,
  },
  {
    key: 'otp-auth-flows',
    applies: hasAuth,
    prompt: `Review the OTP and authentication flows against mobile-otp-guide.md, which is the
backend contract. Read that file before judging.

Flag:
- a countdown or expiry hardcoded instead of driven from the send response's expires_in
- a resend enabled sooner than 60s after ANY send, including the automatic one at
  register/login (the first limit the user meets must be our countdown, not a server rejection)
- an auto-retry after a send returns success: false (that burns the hourly/daily budget and
  lengthens the lockout)
- a server 'message' rewritten, replaced with our own copy, or swallowed — they arrive
  pre-translated and must be displayed as-is
- a code reused across purposes or audiences (student verify vs parent verify vs student reset
  vs parent reset are four distinct scopes; each flow starts with a fresh send)
- shared state that leaks between those four scopes — a single timer storage key, a shared
  in-memory code, a mobile number captured in one flow and consumed in another
- a mobile/country_code that differs between the send call and the consume call of one flow
- ASCII-only digit stripping ([^0-9], \\d) applied before normalizing Arabic-Indic digits
- an account-existence tell on the send path (see anti-enumeration)
- after a successful password reset: a retained token, an auto-login, or a route that is not
  the login screen — the server revokes every token including ours
- a verification gate that can be escaped (back handler, deep link, a navigator branch that
  renders another route while unverified)
- branching on a guess instead of on mobile_verified_at`,
  },
  {
    key: 'correctness',
    applies: true,
    prompt: `Review for plain correctness bugs in the changed logic.

Off-by-one, inverted condition, wrong operator, unhandled null/undefined/empty collection,
unawaited promise, swallowed exception, error path that leaves state half written, timezone or
date arithmetic, string vs number comparison, early return that skips cleanup, loop that
mutates what it iterates, a stale closure in a hook, a missing or over-broad useEffect
dependency, a state update after unmount, a race between two async writes.

React Native specifics: a render-phase write to shared/animated state, a listener or timer not
cleaned up, a key that is an array index over a reordering list, an AppState/keyboard
subscription left registered.

For each, give the concrete input or state that triggers it and what goes wrong. If you cannot
construct that scenario, do not report it.`,
  },
  {
    key: 'quiz-invariants',
    applies: hasQuiz,
    prompt: `Review anything touching quizzes against the invariants in CLAUDE.md.

Flag:
- branching on answers.length (or any shape guess) instead of Question.type via the guards in
  src/utils/quizQuestionTypes.ts; treating 'image' as a type (it is not — imageUrl is an
  attachment orthogonal to type and can appear on any question, including paragraph children)
- scoring treated as question-based rather than unit-based (match = one unit per pair,
  paragraph = sum of its children), or totalQuestions labelled "questions" in the UI instead of
  rendered through formatScore()
- xp computed client-side (it is server-derived, 10 per correct unit)
- a submit payload built by hand instead of through buildSubmitPayload — the invariant is
  exactly ONE entry per top-level question, paragraph children nested in subAnswers, match
  echoing the server's leftId/rightId verbatim, unanswered as selectedAnswer: null
- results handling that forgets userAnswers is FLAT in units: a paragraph parent has no row,
  match is one row with match_results, answer_1 is null for both — regroup with
  groupUserAnswers and null-guard
- match pairing read from anything other than the index-aligned matchColumns (left[i] ↔ right[i])
- a change to the match tap state machine that bypasses matchTap in src/utils/matchInteraction.ts,
  or introduces a one-tap steal on the wire board (deliberately absent)
- submit allowed before every left item is paired
- a quiz-taking surface made theme-aware (they are intentionally light-only via QUIZ_COLORS)
  or the review screen made light-only (it stays theme-aware)`,
  },
  {
    key: 'i18n-rtl-design',
    applies: hasUi,
    prompt: `Review user-facing surfaces against the bilingual, RTL, and design-token rules.

Flag:
- a user-facing string not going through t(), or a key added to only one of
  src/i18n/locales/en.json and ar.json; any edit to the stale root /locales directory
- a translation key referenced in code that does not exist in either locale file (renders the
  raw key to the user)
- textAlign set to 'right'/'auto' where the rule is 'left' + native RTL flipping; a TextInput
  that does not use INPUT_TEXT_ALIGN from src/lib/rtl.ts, or that sets textAlign in its style
  as well (the style wins over the prop and pins Arabic to the wrong edge)
- physical left/right layout properties where the logical start/end is meant
- user-supplied text (names, titles, school/city names) rendered without isArabicText(str)
  passed as forceArabic to useTypography
- a bare fontWeight (drops the custom family on Android — typography(style, weight) /
  fontWeight(weight) are the accessors)
- a new inline Arabic-range regex instead of the shared helpers, or \\p{L} anywhere (Hermes
  bundle-load parse error), or a hyphen not last in an assembled character class
- a hardcoded colour, spacing, radius, or font size instead of the tokens in src/config/
- a new interactive element without a kebab-case {screen}-{element} testID
- a duplicated validator instead of src/utils/validators.ts`,
  },
  {
    key: 'tests',
    applies: true,
    prompt: `Review test coverage of the diff.

For each substantive behaviour added or changed in the diff, say whether a test exercises it —
name the test if so, flag it if not. New pure logic in src/utils/ especially should be tested
directly rather than through a mock-heavy hook test.

Then review the tests themselves: an assertion that cannot fail, a mock so complete the test
only tests the mock, a test asserting an implementation detail rather than user-visible
behaviour (this project asserts what the user sees — validation errors, navigation, rendered
text — not that a fetch happened, and never styles), a shared fixture mutated across tests, a
skipped or .only test left in, an async test that does not await its assertion, a test
asserting a behaviour the diff just deleted.

Mocks belong in src/__tests__/__mocks__/ and rendering goes through
src/__tests__/helpers/renderWithProviders.tsx; react-i18next is mocked so t() returns the key —
assertions are on translation keys, not English copy.

Maestro flows: flag a fixed sleep where a visibility wait works, a missing conditional for a
known popup (iOS "Not Now", confirm-modal-ok, profile-completion-skip-button, register
disclaimer, OTP skips), a real production credential in e2e/env.yaml, or a flow that asserts a
testID the diff renamed or removed.

Do NOT propose tests for unchanged code.`,
    effort: 'high',
  },
  {
    key: 'simplification',
    applies: true,
    prompt: `Review for code that should not exist in this diff.

Duplicated knowledge that already lives somewhere in the repo — search before claiming it and
cite the existing implementation. This codebase already has: validators.ts (names, password,
mobile), scoreUtils.ts, quizAnswers.ts, quizResultGroups.ts, quizQuestionTypes.ts,
matchInteraction.ts, parentSlots.ts, queryError.ts, rtl.ts, fonts.ts, and the design tokens in
src/config/. A near-clone of an existing screen or util is the most common instance — say what
to collapse into what.

Also: an abstraction with exactly one caller, a config flag nothing sets, a dead branch,
defensive code for a state that cannot occur, a parameter that is always the same value, a
second way to do something the codebase already does, a component prop that is never passed, an
export nothing imports.

Report each with the specific thing to delete or collapse. Skip anything that is merely a taste
preference.`,
    effort: 'high',
  },
]

const DIMENSIONS = ALL_DIMENSIONS.filter((d) => d.applies)
const skipped = ALL_DIMENSIONS.filter((d) => !d.applies).map((d) => d.key)

log(`Reviewing ${base}...${head} across ${DIMENSIONS.length} dimensions at max effort`)
if (skipped.length) log(`Skipped (no matching files changed): ${skipped.join(', ')}`)
if (!changedFiles.length) log('No changedFiles passed — every dimension ran unfiltered')

// --- Review -> verify, pipelined (no barrier between stages) ---------------

const reviewed = await pipeline(
  DIMENSIONS,
  (d) =>
    agent(`${CONTEXT}\n\n${RULES}\n\n--- YOUR DIMENSION: ${d.key} ---\n${d.prompt}`, {
      label: `review:${d.key}`,
      phase: 'Review',
      effort: d.effort || 'max',
      schema: FINDINGS_SCHEMA,
    }),
  (result, d) => {
    const found = (result && result.findings) || []
    if (!found.length) return []
    // Cap the verification fan-out per dimension so a noisy reviewer cannot
    // blow the agent budget; verify the most severe first.
    const RANK = { blocker: 0, high: 1, medium: 2, low: 3 }
    const ordered = found
      .slice()
      .sort((a, b) => (RANK[a.severity] === undefined ? 9 : RANK[a.severity]) - (RANK[b.severity] === undefined ? 9 : RANK[b.severity]))
    const MAX_VERIFY = 6
    const toVerify = ordered.slice(0, MAX_VERIFY)
    if (ordered.length > MAX_VERIFY) {
      log(`${d.key}: ${ordered.length} findings, verifying the ${MAX_VERIFY} most severe — ${ordered.length - MAX_VERIFY} deferred unverified`)
    }
    return parallel(
      toVerify.map((f) => () =>
        parallel(
          ['does-it-reproduce', 'is-the-rule-real', 'is-it-already-handled'].map((lens) => () =>
            agent(
              `${CONTEXT}\n\n${RULES}\n\nA reviewer claims this defect exists. Your job is to REFUTE it.\n\n` +
                `File: ${f.file}:${f.line}\nCategory: ${f.category}\nSeverity: ${f.severity}\n` +
                `Claim: ${f.summary}\nFailure scenario: ${f.failure_scenario}\nEvidence given: ${f.evidence}\n\n` +
                `Refute it through the "${lens}" lens:\n` +
                `- does-it-reproduce: read the real code and try to construct the failing input. If the ` +
                `scenario cannot actually occur, it is refuted.\n` +
                `- is-the-rule-real: verify the rule it invokes against CLAUDE.md, mobile-otp-guide.md, or ` +
                `the actual config/token files. A misremembered or non-existent rule refutes the finding.\n` +
                `- is-it-already-handled: look for a guard, wrapper, link in src/lib/apollo.ts, shared util, ` +
                `navigator branch, or existing test elsewhere in the repo that already prevents this.\n\n` +
                `Read the actual files — do not judge from the snippet. Default to refuted=true when you ` +
                `are uncertain. A finding that wastes the fixer's time is worse than a missed one.`,
              { label: `verify:${d.key}:${f.file}`, phase: 'Verify', effort: 'max', schema: VERDICT_SCHEMA }
            )
          )
        ).then((votes) => {
          const cast = votes.filter(Boolean)
          const kept = cast.filter((v) => !v.refuted)
          const severities = kept.map((v) => v.corrected_severity).filter((s) => s && s !== 'none')
          return {
            finding: f,
            dimension: d.key,
            survived: kept.length >= 2,
            votes: cast.length,
            upheld: kept.length,
            refutations: cast.filter((v) => v.refuted).map((v) => v.reason),
            severity: severities.length ? severities[0] : f.severity,
          }
        })
      )
    )
  }
)

const judged = reviewed.filter(Boolean).flat().filter(Boolean)
const confirmed = judged.filter((j) => j.survived)
const dropped = judged.filter((j) => !j.survived)

log(`${judged.length} verified findings -> ${confirmed.length} confirmed, ${dropped.length} refuted`)

// --- Completeness critic ---------------------------------------------------

phase('Synthesize')

const RANK = { blocker: 0, high: 1, medium: 2, low: 3 }
const ranked = confirmed
  .map((c) => Object.assign({}, c.finding, { severity: c.severity, dimension: c.dimension, upheld: c.upheld, votes: c.votes }))
  .sort((a, b) => (RANK[a.severity] === undefined ? 9 : RANK[a.severity]) - (RANK[b.severity] === undefined ? 9 : RANK[b.severity]))

const critic = await agent(
  `${CONTEXT}\n\n${RULES}\n\n` +
    `A review of this diff ran across these dimensions: ${DIMENSIONS.map((d) => d.key).join(', ')}.\n` +
    (skipped.length ? `These were skipped as inapplicable: ${skipped.join(', ')}.\n` : '') +
    `It confirmed ${ranked.length} findings:\n` +
    (ranked.length ? ranked.map((f) => `- [${f.severity}] ${f.file}:${f.line} — ${f.summary}`).join('\n') : '(none)') +
    `\n\nYou are the completeness critic. Do not re-review what was covered. Answer only:\n` +
    `1. Which changed file, function, or behaviour did NO dimension actually examine?\n` +
    `2. Which of the burned-before rules above is relevant to this diff but was not checked?\n` +
    `3. Is there a defect class this diff invites that none of the dimension prompts name?\n` +
    `4. Was a dimension skipped that the changed files actually needed?\n\n` +
    `If you find a concrete defect while answering, report it as a finding with the same fields ` +
    `the reviewers used. Otherwise return an empty findings array and say what is uncovered in ` +
    `the gaps field.`,
  {
    label: 'completeness-critic',
    phase: 'Synthesize',
    effort: 'max',
    schema: {
      type: 'object',
      properties: {
        gaps: { type: 'array', items: { type: 'string' } },
        findings: FINDINGS_SCHEMA.properties.findings,
      },
      required: ['gaps', 'findings'],
    },
  }
)

return {
  scope: { base, head, changedFiles: changedFiles.length },
  dimensions: DIMENSIONS.map((d) => d.key),
  skipped_dimensions: skipped,
  confirmed: ranked,
  unverified_from_critic: (critic && critic.findings) || [],
  coverage_gaps: (critic && critic.gaps) || [],
  refuted: dropped.map((d) => ({
    file: d.finding.file,
    line: d.finding.line,
    summary: d.finding.summary,
    upheld: d.upheld,
    votes: d.votes,
    why_refuted: d.refutations,
  })),
  note: 'confirmed = survived >=2 of 3 refutation votes. unverified_from_critic did NOT go through the panel — verify before acting on it.',
}
