/**
 * Which backend the app talks to.
 *
 * The default is chosen by the `debugMode` flag in app.json:
 *   debugMode: true  → https://prs.elbooklets.com/graphql
 *   debugMode: false → https://elbooklets.com/graphql
 *
 * The flag is read at build time via expo-constants and controls the entire
 * app behaviour (API URL, Firebase Remote Config keys, API URL Switcher).
 * Requests themselves go through Apollo (src/lib/apollo.ts), which reads the
 * active URL from ApiUriManager on every operation.
 */

import Constants from 'expo-constants';
import * as SecureStore from 'expo-secure-store';

import { isDebugMode } from './debug';

const PRODUCTION_URL = 'https://elbooklets.com/graphql';
const DEMO_URL = 'https://demo.elbooklets.com/graphql';
export const PRS_URL = 'https://prs.elbooklets.com/graphql';

// Default URL based on app.json > extra.debugMode (set before building)
export const PRIMARY_API_URL =
  Constants.expoConfig?.extra?.debugMode === true ? PRS_URL : PRODUCTION_URL;

/**
 * Cap on every request Apollo makes. RN's fetch otherwise waits on the
 * platform default — up to ~60s on iOS — stranding every awaiting screen on a
 * dead connection.
 */
export const REQUEST_TIMEOUT_MS = 10000;

/**
 * Longer cap for submitting a quiz. Descriptive questions (what_happens /
 * give_a_reason) are graded by AI synchronously inside the mutation, so the
 * response can take far longer than a normal request. Passed per-operation via
 * `context: { fetchOptions: { timeoutMs: SUBMIT_QUIZ_TIMEOUT_MS } }`.
 */
export const SUBMIT_QUIZ_TIMEOUT_MS = 60000;

/**
 * Longer cap for Boki's `aiChat` mutation. It's a synchronous, non-streaming
 * request — the answer is generated by the LLM inside the mutation itself, so
 * it can take far longer than a normal request. Passed per-operation via
 * `context: { fetchOptions: { timeoutMs: AI_CHAT_TIMEOUT_MS } }`.
 */
export const AI_CHAT_TIMEOUT_MS = 60000;

declare let __DEV__: boolean;

// AsyncStorage key for API URL override
export const CUSTOM_API_URL_KEY = 'custom_api_url_override';

// Known valid API endpoints
const KNOWN_API_URLS = [
  'https://elbooklets.com/graphql',
  'https://demo.elbooklets.com/graphql',
  'https://prs.elbooklets.com/graphql',
] as const;

/**
 * Manages the active API URL with a cache for synchronous access.
 * This is essential for components like Apollo Client that need a sync value at initialization.
 */
class ApiUriManager {
  private static activeUrl: string = PRIMARY_API_URL;
  private static isInitialized: boolean = false;

  /**
   * Initializes the manager by reading the custom URL from storage.
   * Call this in App.tsx before rendering.
   */
  static async init(): Promise<string> {
    if (this.isInitialized) return this.activeUrl;

    try {
      const savedUrl = await SecureStore.getItemAsync(CUSTOM_API_URL_KEY);
      if (
        isDebugMode() &&
        savedUrl &&
        KNOWN_API_URLS.includes(savedUrl as (typeof KNOWN_API_URLS)[number])
      ) {
        this.activeUrl = savedUrl;
      } else {
        this.activeUrl = PRIMARY_API_URL;
      }
    } catch (e) {
      if (__DEV__) console.log('Error initializing ApiUriManager:', e);
      this.activeUrl = PRIMARY_API_URL;
    }

    this.isInitialized = true;
    if (__DEV__) console.log('[ApiUriManager] Active URL:', this.activeUrl);
    return this.activeUrl;
  }

  /**
   * Synchronously gets the active URL.
   */
  static getActiveUrl(): string {
    return this.activeUrl;
  }

  /**
   * Updates the active API URL. Only accepts known production/demo URLs.
   * If the URL matches PRIMARY_API_URL, clears the override from storage.
   */
  static async updateUrl(url: string): Promise<void> {
    // Defence in depth: only the *menu rows* leading here were debug-gated, so
    // the switcher itself would still repoint a production build if it were ever
    // reachable another way (deep link, stale screen, a future caller).
    if (!isDebugMode()) {
      if (__DEV__) console.warn('[ApiUriManager] Refused URL switch outside debug mode');
      return;
    }

    // Safety: only accept known URLs
    if (!KNOWN_API_URLS.includes(url as (typeof KNOWN_API_URLS)[number])) {
      if (__DEV__) console.warn('[ApiUriManager] Rejected unknown URL:', url);
      return;
    }

    if (url === PRIMARY_API_URL) {
      // No override needed — clear storage so default kicks in
      await SecureStore.deleteItemAsync(CUSTOM_API_URL_KEY);
    } else {
      await SecureStore.setItemAsync(CUSTOM_API_URL_KEY, url);
    }

    this.activeUrl = url;
    if (__DEV__) console.log('[ApiUriManager] URL updated to:', url);
  }
}

export { ApiUriManager };

/**
 * Resolve a server-relative asset path (badge logos, avatars — the API returns
 * them as "/storage/…") against the *active* backend.
 *
 * Must never be replaced with a hardcoded host: pinning one would make a
 * production build fetch its images from the PRS test server, which is both a
 * broken-image risk and a leak of test infrastructure into the store build.
 * An absolute URL is passed through untouched.
 */
export const resolveAssetUrl = (path?: string | null): string | undefined => {
  if (!path) return undefined;
  if (!path.startsWith('/')) return path;
  // Every known API URL ends in /graphql; the asset origin is what precedes it.
  return ApiUriManager.getActiveUrl().replace(/\/graphql\/?$/, '') + path;
};
