/**
 * Lesson mind map (BKLT-174) — which renderer a lesson's mind map needs.
 *
 * `Lesson.mindMapUrl` used to always be a raster uploaded by an editor. It can
 * now also be an SVG generated by AI, and `Lesson.mindMapMimeType` says which.
 * `<Image>` cannot draw an SVG on either platform, so picking the wrong branch
 * renders nothing at all.
 *
 * Detection is a plain mime-type comparison — never URL or extension sniffing.
 * A generated map is served from a storage route whose path does not have to
 * end in `.svg`, so an extension check would silently misroute it.
 *
 * Anything unknown falls back to the raster path on purpose: that is the safe
 * default for payloads cached before the field existed, and it matches how the
 * feature behaved before mime types were sent at all.
 */

export const SVG_MIME_TYPE = 'image/svg+xml';

export type MindMapKind = 'svg' | 'raster' | 'none';

/**
 * @param url      `Lesson.mindMapUrl`
 * @param mimeType `Lesson.mindMapMimeType` — null exactly when `url` is null
 * @returns `'none'` when there is nothing to show, so callers can skip the
 *          whole section rather than render an empty or broken frame.
 */
export const resolveMindMapKind = (url?: string | null, mimeType?: string | null): MindMapKind => {
  if (!url || url.trim() === '') return 'none';
  return mimeType?.trim().toLowerCase() === SVG_MIME_TYPE ? 'svg' : 'raster';
};

/** Convenience for render gates: is there a mind map worth showing at all? */
export const hasMindMap = (url?: string | null, mimeType?: string | null): boolean =>
  resolveMindMapKind(url, mimeType) !== 'none';
