/**
 * Pull the live backend schema into src/graphql/schema.graphql.
 *
 *   npm run schema:pull                # PRS (default)
 *   SCHEMA_URL=https://... npm run schema:pull
 *
 * The snapshot is committed so codegen (and therefore tsc + the guardme gate)
 * validates every operation in src/graphql/*.graphql against the real backend
 * instead of a hand-maintained partial schema. Refresh it whenever the backend
 * deploys schema changes; never edit it by hand.
 */
import { writeFile } from 'node:fs/promises';
import {
  buildClientSchema,
  getIntrospectionQuery,
  lexicographicSortSchema,
  printSchema,
} from 'graphql';

const DEFAULT_URL = 'https://prs.elbooklets.com/graphql';
const url = process.env.SCHEMA_URL || DEFAULT_URL;
const OUTPUT = new URL('../src/graphql/schema.graphql', import.meta.url);

const response = await fetch(url, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
  body: JSON.stringify({ query: getIntrospectionQuery() }),
});
if (!response.ok) {
  throw new Error(`Introspection request failed: HTTP ${response.status} from ${url}`);
}
const payload = await response.json();
if (!payload.data) {
  throw new Error(`Introspection returned no data from ${url}: ${JSON.stringify(payload.errors)}`);
}

// Sorted for stable diffs — a schema:pull commit shows real backend changes only.
const schema = lexicographicSortSchema(buildClientSchema(payload.data));
const header = `# Generated by \`npm run schema:pull\` from ${url}\n# Do not edit by hand — refresh after backend schema deployments.\n\n`;
await writeFile(OUTPUT, header + printSchema(schema) + '\n');
console.log(`Schema written to src/graphql/schema.graphql from ${url}`);
